source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 5.2.0'
gem 'sqlite3'
gem 'scout_apm'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'activerecord-session_store'
gem 'activeresource'
gem 'hiredis'
gem 'redis', require: ['redis', 'redis/connection/hiredis']
gem 'resque'
gem 'resque-scheduler'
gem 'whenever', require: false
gem 'bootsnap', require: false
gem 'paper_trail'
gem 'paper_trail-association_tracking'
gem 'aasm'
gem 'activemerchant'
gem 'active_merchant_square', git: 'https://github.com/SpiffyStores/active_merchant_square'
gem 'acts_as_list'
gem 'american_date'
gem 'chartkick'
gem 'cocoon'
gem 'countries'
gem 'country_select'
gem 'gon'
gem 'groupdate'
gem 'gutentag'
gem 'hashid-rails'
gem 'validates_timeliness'
gem 'validates_zipcode'
gem 'paperclip'
gem 'paperclip-meta', git: 'https://github.com/KamiHQ/paperclip-meta', branch: 'paperclip-allow-6'
gem 'percentage'
gem 'premailer-rails'
gem 'rails-letsencrypt'
gem 'browser'
gem 'cairo'
gem 'chunky_png'
gem 'faker'
gem 'geokit-rails'
gem 'geonames'
gem 'haml'
gem 'httparty'
gem 'rest-client'
gem 'monetize'
gem 'rmagick', '< 3.0.0'
gem 'rqrcode'
gem 'hpricot'
gem 'prawn'
gem 'will_paginate'
gem 'devise'
gem 'devise-encryptable'
gem 'exception_notification'
gem 'nokogiri'
gem 'puma'
gem 'sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder'
gem 'oj'
gem 'twilio-ruby'
gem 'rswag-api'
gem 'rswag-ui'
gem 'listen'
gem 'rswag-specs'
gem 'rspec-rails'
gem 'factory_bot_rails'
